PRODUCTO = "TABLET"
PRECIO_PRODUCTO = 350
CANTIDAD_PRODUCTO = 3
PRECIO_TOTAL = (PRECIO_PRODUCTO * CANTIDAD_PRODUCTO)
IGV = float(PRECIO_TOTAL) * 0.18
MONTO_PAGAR = (PRECIO_TOTAL + IGV)
print(f"PRODUCTO : {PRODUCTO}")
print(f"PRECIO : {PRECIO_PRODUCTO}")
print(f"CANTIDAD_UND : {CANTIDAD_PRODUCTO}")
print(f"IGV : {IGV}")
print(f"COSTO TOTAL : {PRECIO_TOTAL}")
print(f"MONTO_PAGAR : {MONTO_PAGAR}")